name: HexiAdmin
main: com.hexicraft.h4ukka.HexiAdmin
version: 0.1r0
commands:
    warn:
        description: This is a test command.
        usage: /warn
        permission-message: no perms for test :c
    vote:
        description: Lists voting links.
        usage: /vote
        permission-message: no perms for test :c